name: Keep App Alive (Modify)

on:
  schedule:
    # Run every 10 hours (at 00:00, 10:00, 20:00 UTC)
    - cron: '0 */10 * * *'
  workflow_dispatch: # Allow manual trigger

permissions:
  contents: write

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Update README with timestamp
      run: |
        # Add a timestamp comment to the README
        echo "" >> README.md
        echo "<!-- Last keep-alive: $(date -u +'%Y-%m-%d %H:%M:%S UTC') -->" >> README.md
    
    - name: Setup Git
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
    
    - name: Commit and push
      run: |
        git add README.md
        git commit -m "🤖 Keep app alive - $(date -u +'%Y-%m-%d %H:%M:%S UTC')"
        git push origin main 